apiVersion: v2
name: identity-ui
version: 0.1.0
description: MathTrail Identity UI Service chart
dependencies:
  - name: mathtrail-service-lib
    version: "0.1.1"
    repository: "https://MathTrail.github.io/mathtrail-charts/charts"
